menu:
  #Archives: /archives
  #黄金屋: /favourite
  #时光机: /favourite/time.html
  #关于我: /aboutme
# rss: /atom.xml
description: 
social:
  weibo: 
  github: https://github.com/hu5675
  stack_overflow: 
  facebook: 
  # twitter: https://twitter.com/onlymonniya
  google_plus: 

page_comment: true
logo: /images/avatar.jpg
background:
  cover: /images/background-cover.jpg
  color: cover-purple

archive_date_format: MMM DD
fancybox: true

# duoshuo_shortname: 

# Disqus 
# disqus:
#   enable: true
#   shortname: bboymars    #your name
#   count: true

google_analytics: UA-78918255-1
baidu_tongji: 9cdad07c755fa23f6aced510c6760e87
favicon: /images/avatar-small.png

#mathjax
mathjax: true